name: colorist
description: "Flutter code generator for custom-named color palettes."
repository: https://github.com/tara-pogancev/flutter-colorist-gen
issue_tracker: https://github.com/tara-pogancev/flutter-colorist-gen/issues
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  colorist_annotations:
    path: ../colorist_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  colorist_builder:
    path: ../colorist_builder
