name: colorist_annotations
description: "Annotations package for Colorist - Flutter's custom theme generator package."
repository: https://github.com/tara-pogancev/flutter-colorist-gen
issue_tracker: https://github.com/tara-pogancev/flutter-colorist-gen/issues
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
