targets:
  $default:
    builders:
      colorist_gen_builder|colorist_gen:
        generate_for:
          - lib/**
        options:
          enabled: true

builders:
  colorist_gen:
    import: "package:colorist_gen_builder/colorist_gen_builder.dart"
    builder_factories: ["coloristBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source
