name: colorist_gen_builder
description: Flutter code generator for custom-named color palettes.
repository: https://github.com/tara-pogancev/flutter-colorist-gen
issue_tracker: https://github.com/tara-pogancev/flutter-colorist-gen/issues
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^4.0.2
  source_gen: ^4.0.1
  analyzer: ^8.2.0

  colorist_annotations:
    path: ../colorist_annotations

dev_dependencies:
  flutter_lints: any
