name: colorist_builder
description: "Flutter code generator for custom-named color palettes."
repository: https://github.com/tara-pogancev/flutter-colorist-gen
issue_tracker: https://github.com/tara-pogancev/flutter-colorist-gen/issues
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=7.5.9 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  source_gen: ">=3.0.0 <5.0.0"
  colorist_annotations:
    path: ../colorist_annotations

dev_dependencies:
  flutter_lints: any
